### ISSUE TITLE
How to disable conversion to jpeg?

### ISSUE THREAD

**Issue by harimayco** [henrixapp/pdfcomprezzor#5]
just a stupid question because I'm not so familiar with go lang.
can you give me a hint how to disable conversion to jpeg?
because my pdf result looks weird after compression because images with transparent bg will have black background like this

![image](https://user-images.githubusercontent.com/5478980/149619811-f8d5beed-9ebe-424d-9c93-e59c6496a466.png)

Thank you

**Comment by henrixapp** [comment]
Hi,

Thank you for reporting this issue.

The initial version of this code was not able to handle png inside of pdfs, because it was used for scans only. I have pushed an updated version of the code to the `png_support` branch. In the current version it just allows to delete images that are too big. The problem is that the trick to recycle the ids is not working anymore. You can see this by comparing the outputted id entries.

I will probably have to investigate this further. If you find a way around this, I would be happy to accept a pull request.

Best,

Henrik
